name: random_distribuitions
version: 0.0.2
description: This is a api to gerenate random numbers using gammavariate, expovariate and possion distribuitions.
author: Daniel Beserra Pinto Bandeira <bandeirapbdaniel@gmail.com>
homepage: https://github.com/danielbandeir/dart_random_distribuitions

environment:
  sdk: ">=2.0.0 <3.0.0"

